project:
  type: website
  output-dir: docs

website:
  title: "My Introduction"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - assignments.qmd
      - projects.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full



